name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install luarocks
          sudo luarocks install luacheck
      - name: Lint
        run: sudo make lint
  test:
    name: X64-ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: |
          yarn global add quicktype
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: Provision
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git ~/.local/share/nvim/site/pack/vendor/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-lua/popup.nvim.git ~/.local/share/nvim/site/pack/vendor/start/popup.nvim
          git clone --depth 1 https://github.com/junegunn/vader.vim.git ~/.local/share/nvim/site/pack/vendor/start/vader.vim
          ln -s $(pwd) ~/.local/share/nvim/site/pack/vendor/start
      - name: Run Tests
        run: |
          curl -OL https://raw.githubusercontent.com/norcalli/bot-ci/master/scripts/github-actions-setup.sh
          source github-actions-setup.sh nightly-x64
          make test
          make vader
